### PR TITLE
Added myself to contributors.

### PR DESCRIPTION
**Pull request by jhbruhn**
Because I think I did some stuff.

### CODE REVIEW

**Comment by sgade** [comment]
Thanks, finally something serious.
You could also add a **Contributors** category in the Readme and a CONTRIBUTORS file in the root to show your participation.

That said, I'm not against it...

**Comment by jhbruhn** [comment]
There you are.

**Comment by sgade** [comment]
You're great.

**Comment by jhbruhn** [comment]
I know.

**Comment by cjmoeller** [comment]
Erdbeerkäse

**Pull request merged**
